<!--
 * @Date: 2022-02-28 23:11:12
 * @LastEditors: Lewis
 * @LastEditTime: 2022-02-28 23:22:35
  -->
### 概述：

异步行为是 JavaScript 的基础，但以前的实现不理想。在早期的 JavaScript 中，只支持定义回调函数 来表明异步操作完成。在ECMAScript 6中新增了正式的Promise引用类型，支持优雅地定义和组织异步逻辑。接下来又增加了 async 和 await 关键字定义异步函数的机制。现代的所有浏览器也都支持了Promise，很多浏览器的一些API如 fetch 也以此为基础。它比传统的异步解决方案(回调和事件)更加合理和强大。

#### 1-Promise

````javascript
// 基础案例：异步加载图片
function loadImageAsync(url) {
  return new Promise(function(resolve, reject) {
    const image = new Image();

    image.onload = function() {
      resolve(image);
    };

    image.onerror = function() {
      reject(new Error('Could not load image at ' + url));
    };

    image.src = url;
  });
}
````

##### 1.1-Promise.prototype.then()

作用：为 Promise 实例添加状态改变时的回调函数。**then**方法接收两个回调函数为参数，第一个参数是**resolved**状态的回调函数，第二个参数是**rejected**状态的回调函数，他们都是可选的。

````javascript
// 基础案例
getJSON("/post/1.json")
  .then(post => getJSON(post.commentURL))
  .then(result => console.log("resolved: ", result),err => console.log("rejected: ", err));
````

##### 1.2-Promise.prototype.catch()

作用：用于指定发生错误时的回调函数。是**.then(null, rejection)** 或 **.then(undefined, rejection)**的别名。

````javascript
p.then((val) => console.log('fulfilled:', val))
  .catch((err) => console.log('rejected', err));

// 等同于
p.then((val) => console.log('fulfilled:', val))
  .then(null, (err) => console.log("rejected:", err));
````

> **一般来说，不要在`then()`方法里面定义 Reject 状态的回调函数（即`then`的第二个参数），总是使用`catch`方法。**

一般总是建议，Promise 对象后面要跟`catch()`方法，这样可以处理 Promise 内部发生的错误。例：

````javascript
// 下面的案例中最后错误会抛出到promise的最外层，成了未捕获的错误
const promise = new Promise(function (resolve, reject) {
  resolve('ok');
  setTimeout(function () { throw new Error('test') }, 0)
});
promise.then(function (value) { console.log(value) });
// ok
// Uncaught Error: test
````

补充：catch()方法返回的还是一个promise对象，因此后面可以接着调用.then()方法

##### 1.3-Promise.prototype.finally()





补充中...